### ISSUE TITLE
Test Contribution Badge Process

### ISSUE THREAD

**Issue by ankitguptaindia** [WordPress/test-handbook#19] opened 2024-01-03 13:56 UTC
Test Contribution Badge Process:

Information Source from Brian:[ Link to Slack Conversation](https://wordpress.slack.com/archives/C061GFC038U/p1699485067766429?thread_ts=1699468772.767939&cid=C061GFC038U)

## Current Status:

As per the information received from Brian, the Test Team is utilizing the script mentioned[ here](https://gist.github.com/ironprogrammer/7abcdac3686027363aefd73934b8d36a) to determine whether a contributor has a badge. The script proves to be very helpful in this regard. However, the challenge lies in creating a list of users to whom badges will be assigned.

We can collect the names of contributors from the following sources:

- #core-test triage participants conducting repro or patch testing
- #core <release-party> events
- New contributors list from #core's regular "Week in Core" posts
- Contributor Day events (in-person or online)
- Contributors who write or improve unit or e2e test coverage for WordPress projects (Core, Gutenberg, canonical plugins, etc.)

Manually searching for contributors would not only be time-consuming but also increases the risk of overlooking deserving contributors, especially when searching Test Reports/contributions on each Trac Ticket is challenging.

## Proposed Idea: 

The idea is to create a system for requesting a badge using a Google sheet. When any contributor contributes to the test team and wishes to earn a badge, they can fill in their details on the sheet. Test Team Reps members will periodically check the sheet (every one or two weeks) and compile a list of contributors based on their contribution history.

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-e2487466-7fff-0d11-7e29-77022ceac1f8"><div dir="ltr" style="margin-left:0pt;" align="left">
Contributor Name | WP.org UserName | Slack UserName | Contribution Details
-- | -- | -- | --
[Ankit K Gupta] | [ankit-k-gupta] | [ankit-k-gupta] | [Tested and Added Test Report on track ticket no. #0000]

</div></b>

We can put the Google sheet link in bookmark items in Slack #core-test and also share a blog post so all interested contributors request to get a badge.

## Other Items to Discuss:

- Other alternative way to make this process easier and effective 
- Set Criteria to earn a badge
- Set the time for checking request on the sheet

## Benefits of this approach:

- The system helps reduce the chance of overlooking deserving contributors, ensuring that individuals who have made valuable contributions are appropriately recognized.
- We can save time that would otherwise be spent searching for contributors across various platforms such as core tickets, beta testing participation, and RC releases.

**Comment by ironprogrammer** [comment] 2024-01-03 21:27
Thank you for starting this discussion, @ankitguptaindia 🙌🏻 I agree that the current process imposes undue responsibility on team reps, where contributions can be easily overlooked.

## Badge Requests
With regards to requesting a badge, I recently learned that there is already a self-request team association form on wp.org for the [Test Contributor](https://profiles.wordpress.org/associations/test-contributor/) badge. I found this while researching how the [Training Team handles badge assignment](https://make.wordpress.org/training/handbook/about/team-profile-badges/) (and feel we can learn a lot from how they've improved on contributor recognition for their team).

Perhaps this form could be utilized instead, though it may first require some follow-up in `#meta` to confirm the intended workflow and to have some additional admins assigned to distribute the work (it appears only Tonya is an admin today). Using this tool would remove dependence on a separate system/form.

## Qualification Criteria
Regarding the test criteria, I've started drafting a PR to address https://github.com/WordPress/test-handbook/issues/5, but here are the items I've got so far:

- Submit a [test report](https://make.wordpress.org/test/handbook/test-reports/) for [testing instructions](https://make.wordpress.org/test/handbook/test-reports/testing-instructions/), [issue reproduction](https://make.wordpress.org/test/handbook/test-reports/issue-reproduction/), or [patch testing](https://make.wordpress.org/test/handbook/test-reports/patch-testing/).
- Submit unit or e2e tests that get merged.
- Contribute toward a [Test handbook](https://github.com/wordpress/test-handbook) PR that gets merged.
- Participate in ZIP package builds or default theme tests during a `#core` `<release-party>`.
- Wrangle at a Contributor Day (table lead, technical support, onboarding).

These criteria and the request process could be included on the proposed handbook page (#5).

## Badge Request Response Time
IMHO, confirming and processing requests every 2 to 4 weeks seems prompt enough for recognition, yet gives some leeway to team reps to account for holidays and time off (life happens). The Training Team does a [monthly review](https://make.wordpress.org/training/handbook/about/team-profile-badges/#requesting-a-profile-badge), which still seems fair, and perhaps some consistency between teams would be preferable.

**Comment by ankitguptaindia** [comment] 2024-02-07 17:14
Hello @ironprogrammer,
Thank you for providing the details; they are very helpful in moving to the next step. I have created a Pull Request to add a Handbook page for the Test Team Badge Request Process.

Please take a look and share your valuable feedback.

PR Link- https://github.com/WordPress/test-handbook/pull/20
Doc Version - [Link](https://docs.google.com/document/d/1DKjF-4Z6h2Z1eNL3uzLqjPmdKycQDgySS7SXtlmQHKE/edit)

**Closed** 2024-10-02 20:23 UTC
